name: 'netflixdbt'
version: '1.0'
config-version: 2

profile: 'netflixdbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  netflixdbt:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      dim:
        +materialized: table
      fct:
        +materialized: table